---
site_name: "WWT - cURL & Python Requests Foundations Hands-On"
site_url: "https://wwt.github.io/curl-requests-foundations"
nav:
  - Home:
    - cURL & Python Requests Hands-On Resources: index.md
  - Section 1:
    - Section 1: sections/section_1.md
  - Section 2:
    - Section 2: sections/section_2.md
  - Section 3:
    - Section 3: sections/section_3.md

# Repository
repo_name: "wwt/curl-requests-foundations"
repo_url: "https://github.com/wwt/curl-requests-foundations"
edit_uri: ""

# Configuration
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  language: en
  features:
    - navigation.expand
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.integrate
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  logo: img/logo.svg
  shortcuts:
    help: 191    # ?
    next: 78     # n
    previous: 80 # p
    search: 83   # s
  plugins:
    - search:
        prebuild_index: true

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist
  - pymdownx.tilde
  - toc:
      permalink: true
